blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/muhittincamdali/iOS-Payment-Processing-Framework#readme
    about: Check out the documentation first
  - name: 💬 Discussions
    url: https://github.com/muhittincamdali/iOS-Payment-Processing-Framework/discussions
    about: Ask questions and discuss ideas
